#ifndef __GUI_ITEM_IFACE_H_
#define __GUI_ITEM_IFACE_H_
typedef enum GuiItemActions_e_
{
	GUI_ITEM_ACTION_UP,
	GUI_ITEM_ACTION_DOWN,
	GUI_ITEM_ACTION_SELECT,
	GUI_ITEM_ACTION_EXIT,
	GUI_ITEM_ACTION_MAX
} GuiItemActions_e;
#endif
